default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("NIHONGO_ECOM_DATABASE_PASSWORD", "password") %>
  port: <%= ENV.fetch("DB_PORT", "3306").to_i %>
  host: <%= ENV.fetch("NIHONGO_ECOM_HOST", "db") %>

development:
  primary:
    <<: *default
    database: nihongo_ecom_development

test:
  primary:
    <<: *default
    database: nihongo_ecom_test

staging:
  primary:
    <<: *default
    database: nihongo_ecom_staging
    username: <%= ENV.fetch("DB_USER") { "nihongo_ecom" } %>

production:
  primary:
    <<: *default
    database: nihongo_ecom_production
    username: <%= ENV.fetch("DB_USER") { "nihongo_ecom" } %>
